# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# Additional deployment details for testing in CI/CD (includes temporary database)
version: '3'
services: 
  tolqc-db:
    image: postgres:11
    env_file:
      - ${ENV_FILE}
    ports:
      - 5432:5432
    networks:
      - tolqc
    deploy:
      replicas: 1
  tolqc-db-core-test:
    image: postgres:11
    env_file:
      - ${ENV_FILE}
    environment:
      - POSTGRES_DB=core-test
    networks:
      - tolqc
    deploy:
      replicas: 1
