# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

# This is used for local development only
version: '3.1'

services:
  tolqc-db:
    image: postgres:11
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5435:5432

  tolqc-api:
    build: tolqc-api/.
    image: tolqc-api
    #command: python3 -m swagger_server
    environment:
      - DB_URI
      - TOLQC_URL
      - ELIXIR_CLIENT_ID
      - ELIXIR_CLIENT_SECRET
      - ELIXIR_REDIRECT_URI
      - ELIXIR_JWK
      - MAIL_SENDER
      - MAIL_SENDER_NAME
      - MAIL_USERNAME_SMTP
      - MAIL_PASSWORD_SMTP
      - MAIL_HOST
      - MAIL_PORT
    ports:
      - 8082:80

  tolqc-ui:
    build:
      context: tolqc-ui/.
      dockerfile: Dockerfile.dev
    image: tolqc-ui
    #command: python3 -m swagger_server
    stdin_open: true
    environment:
      - NODE_ENV=development
    ports:
      - 3004:3000
    volumes:
      - './tolqc-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'
    
  tolqc-api-test:
    image: tolqc-api
    command: dockerize
        -wait tcp://tolqc-db:5432 -wait tcp://tolqc-api:80 -timeout 10s
        bash -c "pytest -v"
    environment:
      - DB_URI
      - TOLQC_URL
      - ELIXIR_CLIENT_ID
      - ELIXIR_CLIENT_SECRET
      - ELIXIR_REDIRECT_URI
      - ELIXIR_JWK
      - MAIL_SENDER
      - MAIL_SENDER_NAME
      - MAIL_USERNAME_SMTP
      - MAIL_PASSWORD_SMTP
      - MAIL_HOST
      - MAIL_PORT
    depends_on:
      - tolqc-db
      - tolqc-api

  tolqc-ui-test:
    image: tolqc-ui
    command: yarn test
    stdin_open: true
    environment:
      - NODE_ENV=development
    volumes:
      - './tolqc-ui/app:/usr/src/app'
      - '/usr/src/app/node_modules'
