# SPDX-FileCopyrightText: 2021 Genome Research Ltd.
#
# SPDX-License-Identifier: MIT

openapi: 3.0.0
info:
  title: Tree of Life ToLQC API
  description: API for ToLQC registry
  contact:
    email: tol-platforms@sanger.ac.uk
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 2.1.2
servers:
  - url: http://0.0.0.0:80/api/v1
tags:
- name: viewers
  description: Viewing ToLQC data only
- name: curators
  description: Creating and updating ToLQC data
paths:
  /environment:
    get:
      tags:
      - users
      summary: Gets the nature of the environment (e.g. production/dev)
      description: |
        Gets the nature of the environment (e.g. production/dev)
      operationId: get_environment
      responses:
        "200":
          description: The environment type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Environment'
                x-content-type: application/json
      x-openapi-router-controller: main.controllers.viewers_controller
components:
  schemas:
    User:
      required:
        - name
        - email
        - organisation
        - roles
      type: object
      properties:
        name:
          type: string
          example: "A User"
        email:
          type: string
          example: "user@example.com"
        organisation:
          type: string
          example: "Research Inc"
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
    Role:
      required:
        - role
      type: object
      properties:
        role:
          type: string
          example: "creator"
    Environment:
      required:
        - environment
      type: object
      additionalProperties: false
      properties:
        environment:
          type: string
          enum: [dev, test, staging, production]
          example: dev
  securitySchemes:
    ApiKeyAuth:        # name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: api-key    # name of the header, query parameter or cookie
      x-apikeyInfoFunc: main.controllers.auth_controller.apikey_auth
# security:
#   - ApiKeyAuth: []     # 2) Apply the API key globally to all operations